### ISSUE TITLE
Ignore http/https/www in links

### ISSUE THREAD

**Issue by sympmarc** [estruyf/vscode-microsoft-writingstyleguide#10]
https is called out here:

`- [Simon Doy](https://www.linkedin.com/in/simondoy)`

![image](https://user-images.githubusercontent.com/1295627/123154640-23911d00-d435-11eb-9924-7cd00bfd49e3.png)

**Comment by estruyf** [comment]
I'll add this to the exclusion list! Thanks @sympmarc.

**Comment by estruyf** [comment]
Should now be available with version `0.0.8`.

**Comment by sympmarc** [comment]
Agreed! Thanks for the fix. I'll keep asking for them until my writing is perfect! :)

**Comment by estruyf** [comment]
Keep it coming, let us keep improving it, so that it works for everyone.
